### PR TITLE
hw2 done

### PR DESCRIPTION
**Pull request by b14ckster**

### CODE REVIEW

**Comment by AleksandraMalygina** [comment]
during previous review I suggested to unset the variable related to listID that was archived. However after your changes it seems that another variable is unset before it was used. As a result the last request's tests failed. Please fix this.

**Review by AleksandraMalygina — CHANGES_REQUESTED** [review]
look in the comments

**Comment by b14ckster** [comment]
done

**Review by AleksandraMalygina — APPROVED** [review]
Good job!

**Pull request merged**
